# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'team_score.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeamScore(object):
    def setupUi(self, TeamScore):
        TeamScore.setObjectName("TeamScore")
        TeamScore.resize(320, 240)
        TeamScore.setStyleSheet("QDialog{\n"
                                "background-color:rgb(180, 180, 180)\n"
                                "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(TeamScore)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TeamScore)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.labelTeamScore = QtWidgets.QLabel(TeamScore)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTeamScore.setFont(font)
        self.labelTeamScore.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTeamScore.setObjectName("labelTeamScore")
        self.verticalLayout.addWidget(self.labelTeamScore)

        self.retranslateUi(TeamScore)
        QtCore.QMetaObject.connectSlotsByName(TeamScore)

    def retranslateUi(self, TeamScore):
        _translate = QtCore.QCoreApplication.translate
        TeamScore.setWindowTitle(_translate("TeamScore", "Team Score"))
        self.label.setText(_translate("TeamScore", "Your Team\'s Score : "))
        self.labelTeamScore.setText(_translate("TeamScore", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TeamScore = QtWidgets.QDialog()
    ui = Ui_TeamScore()
    ui.setupUi(TeamScore)
    TeamScore.show()
    sys.exit(app.exec_())
